# Generated by Django 3.2.20 on 2023-08-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
