# Generated by Django 3.2.20 on 2023-08-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_booking_group_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
